name: qr_code_scanner_and_generator_tutorial
description: "A Flutter project for scanning and generating QR codes with animations and an intuitive UI."
publish_to: 'none' # Keep private, remove this line to publish.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Packages for QR code functionality
  mobile_scanner: ^3.5.5
  pretty_qr_code: ^3.0.0

  # Cupertino icons for iOS-like icons
  cupertino_icons: ^1.0.2

  # For toast/snack messages (optional but useful for better user feedback)
  fluttertoast: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets section (add any custom images or fonts if needed)
  # assets:
  #   - assets/images/example.png
